// FRONT/aroundtech_v2/src/Components/Pages/expenses/expenseGestionComponent.jsx
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';

import AddCircleIcon from '@mui/icons-material/AddCircle';
import PictureAsPdfIcon from '@mui/icons-material/PictureAsPdf';
import { Table, Pagination } from 'react-bootstrap';


import MissionService from '../../../Services/missionService';
import NatureMisService from '../../../Services/NatureService';
import ExpenseService from '../../../Services/ExpenseService';
import { exportToPDF } from '../../../Services/pdfService';

import { useUser } from '../../../Contexts/UserContext';
import { Error, Loading } from '../../Modules/loadingError/loadingErrorComponent';

import Utils from '../../../Utils/utils';
import "./expense.css";
//import ExportsService from './../../../Services/exportsService';


export default function ExpenseGestionComponent() {

    const [missions, setMissions] = useState([]);
    const [lstExpenses, setLstExpenses] = useState([]);
    const router = useNavigate();

    // Pagination
    const [currentPage, setCurrentPage] = useState(1);
    const maxPerPage = 5;
    const handlePageChange = (page) => {
        setCurrentPage(page);
    };
    const lastIndex = currentPage * maxPerPage;
    const firstIndex = lastIndex - maxPerPage;
    const dataPageExpense = [...missions].slice(firstIndex, lastIndex);
    const totalPages = Math.ceil(missions.length / maxPerPage);

    // Utilisation du hook useUser
    const contextUser = useUser();
    const loading = contextUser.loading;
    const error = contextUser.error;


    // Charge les données utilisateur et appel fetchData
    useEffect(() => {
        (async () => {
            if (contextUser?.user?.id) {
                const missionsData = await MissionService.loadMissionsByUser(contextUser.user.id);
                setMissions(missionsData);
                const expensesData = await ExpenseService.loadExpensesFromOneUser(contextUser.user.id);
                setLstExpenses(expensesData);
            }
        })()
    }, [contextUser.user]);

    // Redirige vers la page de gestion des dépenses pour une mission donnée
    const redirectToExpensePage = (missionId) => {
        router(`/expenses/${missionId}`, { replace: true });
    };

    // Gére l'exportation des données au format PDF
    const handleExportToPDF = async (event) => {
        const missionId = event.currentTarget.getAttribute("data-mission-id");

        if (!contextUser.user.id) {
            console.error("L'ID de l'utilisateur n'est pas défini");
            return;
        }

        // Récupération des frais associés à la mission et à l'utilisateur
        const mission = await MissionService.loadOneMission(contextUser.user.id, missionId);
        const expenses = await ExpenseService.loadExpensesFromOneMission(contextUser.user.id, missionId);
        const natureInit = await NatureMisService.loadOneNatureMission(mission.natureInit.id);



        //const respNDF = await exportToPDF//ExportsService.exportExpenseToPdf(contextUser.user.id, missionId)
        // Génération du PDF
        exportToPDF(mission, expenses, natureInit);
    };



    // Pour gérer l'état de chargement
    if (loading) {
        console.log(`loading`, loading)
        return <Loading />;
    }

    // Pour gérer l'état d'erreur
    if (error) {
        console.log(`error`, error)
        return <Error />;
    }

    const NOT_SPECIFIED = "Non spécifié";


    return (
        <>
            <h1>Gestion des notes de frais</h1>
            <div className="d-flex flex-column justify-content-center my-4">
                <div className="text-center my-4 mx-4">
                    <Table responsive hover>
                        <thead>
                            <tr>
                                <th className="table-subtitle">Date de début</th>
                                <th className="table-subtitle">Date de fin</th>
                                <th className="table-subtitle">Nature</th>
                                <th className="table-subtitle">Départ</th>
                                <th className="table-subtitle">Arrivée</th>
                                <th className="table-subtitle">Transport</th>
                                <th className="table-subtitle">Frais</th>
                                <th className="table-subtitle">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {(dataPageExpense === undefined || dataPageExpense.length === 0) && (
                                <tr>
                                    <td colSpan={8} className="text-center">
                                        Aucun résultat
                                    </td>
                                </tr>
                            )}

                            {dataPageExpense !== undefined && dataPageExpense.length !== 0 &&
                                dataPageExpense.map(mission => (
                                    <tr key={mission.id}>
                                        <td>{Utils.formatDateTimestampToStr(mission.startDate)}</td>
                                        <td>{Utils.formatDateTimestampToStr(mission.endDate)}</td>
                                        <td>{Utils.capitalizeFirstLetter(mission.natureCur.name) || NOT_SPECIFIED}</td>
                                        <td>{Utils.capitalizeFirstLetter(mission.departCity.name) || NOT_SPECIFIED}</td>
                                        <td>{Utils.capitalizeFirstLetter(mission.arrivalCity.name) || NOT_SPECIFIED}</td>
                                        <td>{Utils.capitalizeFirstLetter(mission.transport.name) || NOT_SPECIFIED}</td>
                                        <td>{Utils.formatAmount(lstExpenses
                                            // Filtre pour avoir les dépenses de la mission actuelle
                                            .filter(expense => expense.mission.id === mission.id)
                                            // Somme tous les montants des dépenses de cette mission sinon 0
                                            .reduce((acc, expense) => acc + expense.amount, 0)) || 0}€</td>

                                        <td >
                                            {/* Si date de fin < à date du jour alors les boutons s'affichent */}

                                            {Utils.compareDateStr(mission.endDate) && (
                                                <div className="button-container-gestion">
                                                
                                                    <button className="button_icon button_gestion" onClick={() => redirectToExpensePage(mission.id)}>
                                                        <AddCircleIcon />
                                                    </button>
                                                
                                                    <button className="button_icon button_pdf" data-mission-id={mission.id} onClick={handleExportToPDF}>
                                                        <PictureAsPdfIcon />
                                                    </button>
                                                </div>
                                            )}
                                        </td>
                                    </tr>
                                ))}
                        </tbody>
                    </Table>
                    <div className="d-flex justify-content-center">
                        <Pagination>
                            {Array.from({ length: totalPages }).map((_, index) => (
                                <Pagination.Item key={index + 1} active={index + 1 === currentPage} onClick={() => handlePageChange(index + 1)}>
                                    {index + 1}
                                </Pagination.Item>
                            ))}
                        </Pagination>
                    </div>
                </div>
            </div>
        </>
    );
}

// ANGULAR/aroundTech/src/app/Pages/expense-gestion/expense-gestion.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { MissionInterface } from 'src/app/Interfaces/mission.interface';
import { UserInterface } from 'src/app/Interfaces/userI.interface';
import { UserService } from 'src/app/Services/user.service';
import { MissionService } from './../../Services/mission.service';
import { ExportsService } from './../../Services/exports.service';



@Component({
  selector: 'app-expense-gestion',
  templateUrl: './expense-gestion.component.html',
  styleUrls: ['./expense-gestion.component.css']
})
export class ExpenseGestionComponent implements OnInit, OnDestroy {


  // TS variables
  private _subUser!: Subscription;
  private _subLstMissions!: Subscription;

  // HTML variables
  userCur!: UserInterface;
  showTab: boolean = false;
  lstMissions: MissionInterface[] = [];


  constructor(private _UserService: UserService, private _MissionService: MissionService, private _ExportService: ExportsService, private _router: Router) {
  }


  // Actions details
  onClickSee(idMission: number) {
    this._router.navigateByUrl("/missions/" + idMission);
  }

  async onClickExportToPdf(idMission: number) {
    console.log(`exportToPdf`, idMission);
    const responseExportToPdf = await this._ExportService.exportExpenseToPdf(idMission);
    if (responseExportToPdf.status === 200) {
      console.log(`isOkay`, responseExportToPdf)
    } else {
      console.log(`erreur à l'exportation`, responseExportToPdf)
    }
  }



  // Hooks


  async ngOnInit(): Promise<void> {

    this._subUser = this._UserService.userCur$.subscribe(user => {
      this.userCur = user;
    });


    const responseLstMissions = await this._MissionService.getlstMissionByOneUser();

    console.log(`resLstMissions in ExpenseGection`, responseLstMissions)

    if (responseLstMissions.status === 200 && responseLstMissions.obj != null) {
      this._subLstMissions = this._MissionService.lstMissions$.subscribe(mission => {
        this.lstMissions = mission;
      });

    } else {
      console.log(`fail response`, responseLstMissions)
    }

    console.log(`lstMissions`, this.lstMissions)
    this.showTab = this.lstMissions.length > 0 ? true : false;
  }

  ngOnDestroy(): void {
    this._subUser.unsubscribe();
    this._subLstMissions.unsubscribe();
  }
}

<section>
	<h1>Gestion des notes de frais</h1>
	<div class="d-flex flex-column justify-content-center my-4">
		<div class="text-center my-4 mx-4">
			<table  class="table table-striped table-hover" aria-describedby="table mission">
				<thead >
					<tr>
						<th scope="col" class="table-subtitle">Date de début</th>
						<th scope="col" class="table-subtitle">Date de fin</th>
						<th scope="col" class="table-subtitle">Nature</th>
						<th scope="col" class="table-subtitle">Départ</th>
						<th scope="col" class="table-subtitle">Arrivée</th>
						<th scope="col" class="table-subtitle">Transport</th>
						<th scope="col" class="table-subtitle">Frais</th>
						<th scope="col"class="table-subtitle">Actions</th>
					</tr>
				</thead>
				<tbody>

					<tr>
						<td *ngIf="lstMissions?.length === 0" colSpan=8 class="text-center">
							Aucun résultat
						</td>
					</tr>
					<tr id="{{mission.id}}" *ngFor="let mission of lstMissions">
						<td>{{mission.startDate | date : 'Y/MM/dd'}}</td>
						<td>{{mission.endDate | date : 'Y/MM/dd'}}</td>
						<td>{{mission.natureCur.name | titlecase}}</td>
						<td>{{mission.departCity.name | titlecase}}</td>
						<td>{{mission.arrivalCity.name | titlecase}}</td>
						<td>{{mission.transport.name | titlecase}}</td>
						<td>{{mission.totalExpenses }} €</td>

						<td >
							<div *ngIf="mission.editable" class="button-container-gestion">
								<i class="fa-solid fa-circle-plus btn button_icon button_gestion" (click)="onClickSee(mission.id)"></i>
								<i class="fa-solid fa-file-pdf  btn button_icon button_pdf" (click)="onClickExportToPdf(mission.id)"></i>
							</div>
						</td>
					</tr>

				</tbody>
			</table>
			<!-- <div class="d-flex justify-content-center">
            <Pagination>
                {Array.from({ length: totalPages }).map((_, index) => (
                <Pagination.Item key={index + 1} active={index + 1===currentPage} onClick={()=> handlePageChange(index +
                    1)}>
                    {index + 1}
                </Pagination.Item>
                ))}
            </Pagination>
        </div> 
	-->
		</div>
    </div>
</section>
