// ANGULAR/aroundTech/src/app/Pages/home/home.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { UserInterface } from 'src/app/Interfaces/userI.interface';
import { UserService } from 'src/app/Services/user.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})

export class HomeComponent implements OnInit, OnDestroy {

  // TS variables
  private _subUser !: Subscription;

  // HTML variables
  userCur !: UserInterface;

  constructor(private _userService: UserService,  private _router: Router) {
  }




  ngOnInit(): void {

    this._subUser = this._userService.userCur$.subscribe( user => this.userCur = user);

    console.log(`userCur home`,this.userCur)
    if (!this.userCur.logged) {
      //this._router.navigateByUrl("/login");
      throw new Error("Utilisateur non trouvé");
    }
  }


  ngOnDestroy(): void {
    this._subUser.unsubscribe();
  }

}


<section id="home">
    <h1>Bienvenue sur l'application de Gestion Des Missions</h1>
    <div class="userInfo">
        <div class="userName">Bonjour, {{userCur.firstname | titlecase }}</div>
    </div>
    <div class="citation">
        "Le succès n'est pas final, l'échec n'est pas fatal : c'est le courage de continuer qui compte." <br /> — Winston Churchill
    </div>
</section>

// FRONT/aroundtech_v2/src/Components/home/home.jsx
import styles from './page.module.css';
import { useUser } from '../../Contexts/UserContext';
import { Error, Loading } from '../loadingError/loadingErrorComponent';

export default function Home() {

    // Utilisation du hook useUser
    const contextUser = useUser();
    const loading = contextUser.loading;
    const error = contextUser.error;


    if (loading) {
        return <Loading />;
    }

/*     if (error) {
        return <Error />;
    }
 */
    const userName = contextUser.user ? `${contextUser.user.firstname} ${contextUser.user.lastname}` : "Utilisateur";

    return (
        <main>
            <h1>Bienvenue sur l'application de Gestion Des Missions</h1>
            <div className={styles.userInfo}>
                <div className={styles.userName}>Bonjour, {userName}</div>
            </div>
            <div className={styles.citation}>
                "Le succès n'est pas final, l'échec n'est pas fatal : c'est le courage de continuer qui compte." <br /> — Winston Churchill
            </div>
        </main>
    )
}
