// FRONT/aroundtech_v2/src/Components/login/loginComponent.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';

import { Button, Card, Col, Container, Form, Row, Image } from 'react-bootstrap';
import { Alert, TextField } from '@mui/material';
import logo from "../../Assets/images/around-tech-logo.png";
import './login.css';
import userService from '../../Services/UserService';
import { useUser } from '../../Contexts/UserContext';

const LoginComponent = () => {

  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const router = useNavigate();
  const contextUser = useUser();

  const handleLogin = async (event) => {
    event.preventDefault();

    // Réinitialise l'erreur
    setError('');

    try {

      const response = await userService.getOneUser(email, password);

      console.log(`response login `, response)

      if (response.email !== "") {

        contextUser.updateUser(response);
        // Redirection vers la page d'accueil si la connexion est réussie
        //router.push('/');
        console.log(` login is find redirection!!! `, response)
        router('/', { replace: true });

      } else {
        console.log(`test no connect`, response)
        // Message d'erreur si la connexion échoue
        const errorData = await response.json();
        setError(errorData.message);
      }
    } catch (error) {
      console.log(`errrur login`, error)
      // Gestion des erreurs lors de l'appel à l'API
      setError('Impossible de se connecter au serveur.');
    }
  };

  return (
    <Container>
      <Row className="justify-content-md-center mt-5 pt-5">
        <Col md={6} >
          <Card className="login_card">
            <Card.Body>
              <div className="d-flex justify-content-center pt-2">
                <Image
                  src={logo}
                  className="logo "
                  height={100}
                  width={100}
                  alt="Around Tech Logo"
                />
              </div>

              <h1>Gestion des missions</h1>
              <Form onSubmit={handleLogin}>
                <div >
                  <TextField
                    variant="outlined"
                    margin="normal"
                    required
                    fullWidth
                    id="email"
                    label="Adresse email"
                    name="email"
                    autoComplete="email"
                    autoFocus
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                  />
                  <TextField
                    variant="outlined"
                    margin="normal"
                    required
                    fullWidth
                    name="password"
                    label="Mot de passe"
                    type="password"
                    id="password"
                    autoComplete="current-password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                  />
                  <div className="d-flex justify-content-center mt-4">
                    <Button type="submit" className="button_connect mb-3">
                      Se connecter
                    </Button>
                  </div>

                </div>
                {error && <Alert severity="error">{error}</Alert>}
              </Form>
            </Card.Body>
          </Card>
        </Col>
      </Row>
    </Container>
  );
};

export default LoginComponent;

// ANGULAR/aroundTech/src/app/Pages/login/login.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { NgForm } from '@angular/forms';
import { Router } from '@angular/router';
import { LoginInterface } from 'src/app/Interfaces/login.interface';
import { Validators } from '@angular/forms';
import { UserInterface } from 'src/app/Interfaces/userI.interface';
import { UserService } from 'src/app/Services/user.service';
import { Subscription } from 'rxjs';
@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit, OnDestroy {

  // HTML variables
  loginCur !: LoginInterface;
  emailLogin!: string;
  pwdLogin!: string;
  loginAlert: string = "";
  userCur !: UserInterface;

  // TS variables
  private _subUser  !: Subscription;
  

  constructor(private _userService: UserService, private _router: Router) {
  }



  onSubmitConnect = async (formLogin: NgForm) => {

    if (formLogin.valid) {


      let loginObj = new LoginInterface(formLogin.value.emailInput, formLogin.value.pwdInput);

      const response = await this._userService.getOneUser(loginObj);
      console.log(`respon GetOneUser`, response)
      if (response.obj !== null && response.status === 200) {
        this._router.navigateByUrl("home");
      } else {
        this.loginAlert = response.message; 
      }


    } else {
      console.log(`c'est raté`)
      console.log(`form`, formLogin)
      console.log(`form`, formLogin.value)
    }
  }


  ngOnInit(): void {

    this._subUser = this._userService.userCur$.subscribe(user => { this.userCur = user });
    console.log(`onINIT login`, this.userCur)
    if (this.userCur.logged != false){
      this._router.navigateByUrl("home");
    }

    // Test DEV à suppr
    this.loginCur = new LoginInterface("lol@ex.lol", "John");
  }

  ngOnDestroy(): void {
    this._subUser.unsubscribe();
  }
}

<div class="container">
	<div class="justify-content-md-center mt-5 ">
		<div class="md-6">
			<div class="card login_card">
				<div class="card-body">

					<div class="d-flex justify-content-center pt-2">
						<img src="./assets/images/around-tech-logo.png" className="logo " height="100" width="100"
							alt="Around Tech Logo" />
					</div>

					<h1 >Gestion des missions</h1>

					<div *ngIf="loginAlert !== ''" class="alert">
						<p>{{loginAlert}}</p>
					</div>
					
					<form #formLogin="ngForm" (ngSubmit)="onSubmitConnect(formLogin)" >
						<div class="form-input">

							<div class="form-floating mb-3">
								<input type="email" class="form-control" id="emailInput" name="emailInput" placeholder="Email" autoComplete="email" required 
									[(ngModel)]="loginCur.email"
									#email="ngModel"
									email="true"
								>
								<label for="emailInput">Email</label>
							
								<div *ngIf="email.invalid && (email.dirty || email.touched)" class="alert">
									<p *ngIf=" email.errors?.['email']">Adresse mail non valide</p>
								</div>
							</div>

							<div class="form-floating mb-3">
								<input type="password" class="form-control" id="pwdInput" name="pwdInput" placeholder="Password" autoComplete="current-password" required 
									[(ngModel)]="loginCur.pwd"
									#pwd="ngModel"
									pwd="true"
								>
								
								<label for="pwdInput">Mot de passe</label>
						
								<div *ngIf="pwd.invalid && (pwd.dirty || pwd.touched)" class="alert">
									<p *ngIf="pwd.errors?.['required']">Un mot de passe est requis</p>
								</div>
							</div>


							<div id="contBtnConnect" class="d-flex justify-content-center">
								<Button type="submit" class="button_connect btn mb-3" [disabled]="!formLogin.valid">Se connecter</Button>
							</div>

						</div>

					</form>

				</div>
			</div>
		</div>
	</div>
</div>
