// FRONT/aroundtech_v2/src/Components/root/footer/footer.jsx

import React from 'react';
import {Image } from 'react-bootstrap';
import { useNavigate } from 'react-router-dom';
import logo from "../../../Assets/images/around-tech-logo.png";
function Footer() {
  
  // Pour ajouter du css dynamique
  const pathname = useNavigate();

  // Obtient l'année courante
  const currentYear = new Date().getFullYear();

  return (
    <footer className= {`d-flex justify-content-center align-items-center border-top ${pathname === '/' ? 'footer-home' : ''}`}>
      <div>
        <a href="/" className="d-flex align-items-center justify-content-center link-body-emphasis text-decoration-none">
          <Image
            src={logo}
            className="logo"
            height={100}
            width={100}
            alt="Around Tech Logo"
          />
        </a>
        <span>Copyright © {currentYear} AroundTech. Tous droits réservés.</span>
      </div>
    </footer>
  );
}

export default Footer;

// ANGULAR/aroundTech/src/app/Components/footer/footer.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent {

  // HTML variables
  currentYear: number = new Date().getFullYear();

}

<footer class="d-flex justify-content-center align-items-center border-top footer-home ">
    <div>
        <a routerLink="/home"
            className="d-flex align-items-center justify-content-center link-body-emphasis text-decoration-none">
            <img src="../../../assets/images/around-tech-logo.png" className="logo" height=50 width=50 alt="Around Tech Logo" />
        </a>
        <br/>
        <span>Copyright © {{currentYear}} AroundTech. Tous droits réservés.</span>
    </div>
</footer>
